FROM ubuntu:latest AS build

RUN apt-get update
RUN apt-get install openjdk-21-jdk -y
RUN apt-get install maven -y

# Definir argumentos para variáveis de ambiente
ARG DATABASE_HOST
ARG DATABASE_PORT
ARG DATABASE_NAME
ARG DATABASE_USER
ARG DATABASE_PASSWORD
ARG JWT_SECRET_KEY
ARG GMAIL_APP_EMAIL
ARG GMAIL_APP_PASSWORD

# Configurar as variáveis de ambiente para o build
ENV DATABASE_HOST=${DATABASE_HOST}
ENV DATABASE_PORT=${DATABASE_PORT}
ENV DATABASE_NAME=${DATABASE_NAME}
ENV DATABASE_USER=${DATABASE_USER}
ENV DATABASE_PASSWORD=${DATABASE_PASSWORD}
ENV JWT_SECRET_KEY=${JWT_SECRET_KEY}
ENV GMAIL_APP_EMAIL=${GMAIL_APP_EMAIL}
ENV GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}

WORKDIR /app
COPY Backend/ /app/

# Pular testes para evitar problemas de ambiente
RUN mvn clean install -DskipTests

FROM openjdk:21-jdk-slim

# Definir mesmos argumentos para a imagem final
ARG DATABASE_HOST
ARG DATABASE_PORT
ARG DATABASE_NAME
ARG DATABASE_USER
ARG DATABASE_PASSWORD
ARG JWT_SECRET_KEY
ARG GMAIL_APP_EMAIL
ARG GMAIL_APP_PASSWORD

# Configurar as variáveis de ambiente para runtime
ENV DATABASE_HOST=${DATABASE_HOST}
ENV DATABASE_PORT=${DATABASE_PORT}
ENV DATABASE_NAME=${DATABASE_NAME}
ENV DATABASE_USER=${DATABASE_USER}
ENV DATABASE_PASSWORD=${DATABASE_PASSWORD}
ENV JWT_SECRET_KEY=${JWT_SECRET_KEY}
ENV GMAIL_APP_EMAIL=${GMAIL_APP_EMAIL}
ENV GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}

EXPOSE 8080

WORKDIR /app
COPY --from=build /app/target/murall-0.0.1-SNAPSHOT.jar /app/appmurall.jar
ENTRYPOINT ["java", "-jar","appmurall.jar"]